hf/urls.py
from django.urls import path

from . import views

app_name = 'hf'
urlpatterns = [
    path('', views.index, name='index'),
    path('api/games/', views.apiGames, name='apiGames'),
    path('api/games/<slug:game_id>/', views.apiGetGame, name='apiGetGame'),
    path('api/games/<slug:game_id>/players/', views.apiPlayers, name='apiPlayers'),
    path('api/games/<slug:game_id>/sessionplayer/', views.apiGetSessionPlayer, name='apiGetSessionPlayer'),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('chat/<str:room_name>/setName/', views.setName, name='setName'),
    path('debug/<str:room_name>/', views.debugSession, name='debugSession'),
    path('join/<slug:game_id>/', views.joinGame, name='joinGame'),
    path('join/<slug:game_id>/addPlayer/', views.addPlayer, name='addPlayer'),
    path('join/<slug:game_id>/joinTeam/<int:team_id>/', views.joinTeam, name='joinTeam'),
    path('join/<slug:game_id>/addTeam/', views.addTeam, name='addTeam'),
    path('games/<slug:game_id>/', views.gameDetailWS, name='gameDetailWS'),
    path('createGame/', views.createGame, name='createGame'),
    path('new/', views.gameCreate, name='gameCreate'),
    path('players/create/', views.playerCreate, name='playerCreate'),
]

hf/models.py
from django.db import models
from django.utils.crypto import get_random_string
from django.contrib.sessions.models import Session
from django.forms.models import model_to_dict

# Create your models here.


class Game(models.Model):
    STATUS_AWAITING = 1
    STATUS_IN_PROGRESS = 2
    STATUS_COMPLETED = 3
    STATUS_CHOICES = [
            (STATUS_AWAITING, 'Awaiting Players'),
            (STATUS_IN_PROGRESS, 'Game in-progress'),
            (STATUS_COMPLETED, 'Completed'),
    ]
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(
            primary_key=True,
            default=(lambda: get_random_string(length=8)),
            editable=False,
            max_length=8
    )
    status = models.SmallIntegerField(
            choices=STATUS_CHOICES,
            default=STATUS_AWAITING
    )
    name = models.CharField(
            max_length=256
    )
    draw_pile = models.TextField(default='')
    discard_pile = models.TextField(default='')
    current_turn = models.IntegerField(default=0)
    game_num = models.IntegerField(default=0)

    def __str__(self):
        return self.id + ': ' + self.STATUS_CHOICES[self.status-1][1]

    def to_json(self):
        result = model_to_dict(self)
        result['display_name'] = self.name
        result['name'] = f'games/{self.id}'
        result['draw_pile'] = len(result['draw_pile']) // 2
        result['discard_pile'] = len(result['discard_pile']) // 2

        return result


class Team(models.Model):
    name = models.CharField(
            max_length=64
    )
    game = models.ForeignKey(
            Game,
            on_delete=models.CASCADE,
            related_name='teams'
    )
    current_turn = models.IntegerField(default=0)
    books = models.TextField(default='')
    total_score = models.IntegerField(default=0)


class Player(models.Model):
    session = models.ForeignKey(
            Session,
            on_delete=models.SET_NULL,
            null=True
    )
    game = models.ForeignKey(
            Game,
            on_delete=models.CASCADE,
            related_name='players'
    )
    team = models.ForeignKey(
            Team,
            on_delete=models.SET_NULL,
            null=True,
            related_name='players'
    )
    name = models.CharField(
            max_length=32,
            default="unnamed_player"
    )
    hand = models.TextField(default='')
    foot = models.TextField(default='')

    def to_json(self):
        result = model_to_dict(self)
        result['display_name'] = result['name']
        result['name'] = f'games/{self.game.id}/players/{self.pk}'
        result['foot'] = len(self.foot) > 0
        result['team'] = f'games/{self.game.id}/teams/{self.team.pk}' if self.team else None
        result['game'] = f'games/{self.game.id}'

        return result

hf/templates/hf/gameCreate.html
<!Doctype html>
<head>
    <body>
        <h1>Create a new game</h1>
        <p>Enter a name for your game lobby: (Optional)</p>
        <form action="{% url 'hf:createGame' %}" method="post">
            {% csrf_token %}
            <input id='new-game-name' type='text' name='new-game-name'/><br/>
            <input id='new-game-create' type='submit' value='Create Game'/><br/>
        </form>
    </body>
<head>

hf/templates/hf/gameDetail.html
<!Doctype html>
<html>
    <body>
        <h1>Game Details</h1>
        <h4>Copy this link to invite players to your game: {% url 'hf:joinGame'  game.id %}</h4>
        <p>Game status: {{ game.get_status_display }}</p>
        <h2>Player List:</h2>
        {% for team in game.teams.all %}
            <h3>{{ team.name }}</h3>
            <form action="{% url 'hf:joinTeam' game.id team.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Join">
            </form>
            <ul>
            {% for player in team.players.all %}
                <li>{{ player.session.get_decoded.name }}
            {% endfor %}
            </ul>
        {% endfor %}
        <form action="{% url 'hf:addTeam' game.id %}" method="post">
            {% csrf_token %}
            <input name="teamname" type="text" id="teamname"><br/>
            <input type="submit" value="Create New Team">
        </form>
        <h3>Players not on a team</h3>
        <ul>
        {% for player in game.players.all %}
            {% if not player.team %}
                <li>{{ player.session.get_decoded.name }}
            {% endif %}
        {% endfor %}
        </ul>
    </body>
</html>

hf/templates/hf/gameDetailWS.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Hand & Foot | Game Id: {{game.id}}</title>
        {% load static %}
        <script src="{% static 'game.js' %}" defer></script>
    </head>
    <body>
        <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
        <input id="chat-message-input" type="text" size="100"/><br/>
        <input id="chat-message-submit" type="button" value="Send"/>
        <div id="game-area">
            <h1>Game Details</h1>
            <h4>Copy this link to invite players to your game: {% url 'hf:joinGame'  game.id %}</h4>
            <input id="game-start" type="button" value="Start Game"/>
            <p>Game status: {{ game.get_status_display }}</p>
            <input id="game-team-input" type="text"/><br/>
            <input id="game-team-submit" type="button" value="Create New Team"/>
            <div id="game-player-list">
                Loading Game Data...
            </div>
        </div>
    </body>
</html>

hf/templates/hf/index.html
<a href="{% url 'hf:gameCreate' %}">Create a new game</a>
{% if game_list %}
    <ul>
    {% for game in game_list %}
    <li><a href="{% url 'hf:gameDetailWS' game.id %}">{{ game.name }} ({{game.id}})</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No games are available.</p>
{% endif %}

hf/templates/hf/joinGame.html
<!Doctype html>
<html>
    <head>
        <title>Join Game: {{ game.id }}</title>
    </head>
    <body>
        {% if error_msg %}
            <p><strong>{{ error_msg }}</strong></p>
        {% endif %}
        <form action="{% url 'hf:addPlayer' game.id %}" method="post">
            {% csrf_token %}
            <label for="username">Create a username</label><br/>
            <input name="username" type="text" id="username">
            <input type="submit" value="Create">
        </form>
    </body>
</html>

hf/templates/hf/room.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chat Room</title>
    </head>
    <body>
        <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
        <input id="chat-message-input" type="text" size="100"/><br/>
        <input id="chat-message-submit" type="button" value="Send"/>
    </body>
    <script>
        var roomName = {{ room_name_json }};

        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/hf/chat/' + roomName + '/');

        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var message = data['message'];
            document.querySelector('#chat-log').value += (message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            var messageInputDom = document.querySelector('#chat-message-input');
            var message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));

            messageInputDom.value = '';
        };
    </script>
</html>

hf/templates/hf/setname.html
<!Doctype html>
<html>
    <body>
        <h1>Enter your name</h1>
        <form action="{% url 'hf:setName' room_name %}" method="post">
            {% csrf_token %}
            <input id='new-session-name' type='text' name='new-session-name'/><br/>
            <input id='new-session-create' type='submit' value='Submit'/><br/>
        </form>
    </body>
</html>